language: java
jdk:
- oraclejdk8
os:
- linux
script: mvn install -Pinstall-runtime
before_script:
- sudo apt-get update -qq
- sudo apt-get install -y rpm
- sudo apt-get install -y wget
- wget http://download-aws.ej-technologies.com/install4j/install4j_unix_6_0.tar.gz
- tar zxvf install4j_unix_6_0.tar.gz
- wget -O /home/travis/build/asciidocfx/AsciidocFX/install4j6/jres/macosx-amd64-1.8.0_25.tar.gz http://asciidocfx.com/jres/macosx-amd64-1.8.0_25.tar.gz
- wget -O /home/travis/build/asciidocfx/AsciidocFX/install4j6/jres/windows-amd64-1.8.0_25.tar.gz http://asciidocfx.com/jres/windows-amd64-1.8.0_25.tar.gz
- wget -O /home/travis/build/asciidocfx/AsciidocFX/install4j6/jres/windows-x86-1.8.0_25.tar.gz http://asciidocfx.com/jres/windows-x86-1.8.0_25.tar.gz
- wget -O /home/travis/build/asciidocfx/AsciidocFX/install4j6/jres/macosx-amd64-1.8.0_25_unpacked.tar.gz http://asciidocfx.com/jres/macosx-amd64-1.8.0_25_unpacked.tar.gz
- mvn clean
- mvn install4j:install-license -DlicenseKey=[LicenseKey]
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: L4y+3fi/yVR7guv7cynzrTOjRbE4+JTK79Fv5J8IQFwtzTP4V2GeW5ZjTdZXAlsFRvak5zhxY4OEYbYI2/riMib5Ea/K28Fd0F/nK8bUDddzxyXPc8zj6VrQINJX8Na2KfPvXT2UR+LtUWkK5HjeR+O/YQPTO4M+7SDGx5P+gog=
  file:
    - /home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_windows_installer.exe
    - /home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_windows_archive.zip
    - /home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_macos_single_installer.dmg
    - /home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_macos_single_archive.dmg
    - /home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_macos_folder_installer.dmg
    - /home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_macos_folder_archive.dmg
    - /home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_linux_installer.sh
    - /home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_linux_deb.deb
    - /home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_linux_archive.tar.gz
  on:
    tags: true
    all_branches: true
    repo: asciidocfx/AsciidocFX
env:
  global:
    secure: X6FF34waMpLTsIQD9JdK6lM635nJKLy0HNqoAEW0sdADcKuolwrP42oTZ5VdnOnwrvPa8+lrK7PIfQeuZMK9g/TKrzLevSuCh6dzSeqQ+eOgJSOHFwkaR4wBG0XcmgNiIO+YXAuuOALv1wtdrV9oakbRFJ0HCVeixGS5/Ya2IWo=
